@extends('layouts.app') @section('title','Sursa datelor') @section('content')
<div class="page-head"><div><p class="eyebrow">Trasabilitate și stare</p><h1>Sursa datelor</h1><p>Toți furnizorii și starea ultimei verificări, într-o singură vedere.</p></div><div class="source-counts"><span><b>{{ $sources->where('status','healthy')->count() }}</b> disponibile</span><span><b>{{ $sources->count() }}</b> total</span></div></div>
<div class="source-note"><i data-lucide="info" size="16"></i><span>„Verifică acum” testează conexiunea și importă automat în MySQL toate înregistrările detectate, fără duplicate.</span></div>
<section class="card source-table-card"><div class="source-table-wrap"><table class="source-table"><thead><tr><th>Sursă</th><th>Date furnizate</th><th>Stare</th><th>Ultima verificare</th><th>Date importate</th><th>Rezultat</th><th class="source-action-head">Acțiune</th></tr></thead><tbody>
@foreach($sources as $source)
<tr>
    <td data-label="Sursă"><div class="source-name"><span class="source-mini-icon"><i data-lucide="{{ $source->category==='Cote și piețe'?'badge-dollar-sign':'database' }}" size="16"></i></span><div><b>{{ $source->name }}</b><a href="{{ $source->website_url }}" target="_blank" rel="noreferrer">Deschide site-ul <i data-lucide="external-link" size="11"></i></a></div></div></td>
    <td data-label="Date furnizate"><span class="source-data-type">{{ $source->category }}</span>@if($source->credential_env)<small class="source-key"><i data-lucide="key-round" size="11"></i>{{ $source->credential_env }}</small>@endif</td>
    <td data-label="Stare"><span class="source-status {{ $source->status }}"><span></span>{{ $source->status_label }}</span></td>
    <td data-label="Ultima verificare" class="source-last-check {{ !$source->last_checked_at || !$source->last_checked_at->isToday() ? 'is-stale' : '' }}">@if($source->last_checked_at)<b class="source-time">{{ $source->last_checked_at->format('d.m.Y · H:i') }}</b><small>{{ $source->last_checked_at->diffForHumans() }} · {{ $source->last_duration_ms }} ms</small>@else<b class="source-time">Niciodată</b><small>{{ $source->is_configured ? 'Rulează prima verificare' : 'Necesită configurare' }}</small>@endif</td>
    <td data-label="Date importate"><span class="source-import-count">{{ number_format($source->records_count) }}</span><small>înregistrări în MySQL</small></td>
    <td data-label="Rezultat"><span class="source-result" title="{{ $source->last_message }}">{{ $source->last_message ?: 'Nicio verificare efectuată.' }}</span>@if($source->records_checked)<small>{{ number_format($source->records_checked) }} înregistrări detectate</small>@endif @if($source->slug==='sportmonks' && data_get($source->metadata,'superliga_coverage'))<div class="source-coverage"><b>SuperLiga România</b>@foreach(data_get($source->metadata,'superliga_coverage.capabilities',[]) as $capability=>$state)<span class="{{ $state==='available'?'available':'unavailable' }}">{{ ['fixtures'=>'Fixtures','statistics'=>'Statistici','absences'=>'Accidentări','xg'=>'xG','odds'=>'Cote'][$capability]??$capability }}: {{ $state==='available'?'Disponibil':'Indisponibil' }}</span>@endforeach</div>@endif</td>
    <td data-label="Acțiune" class="source-action">@if($source->is_configured)<form method="post" action="{{ route('data-sources.verify',$source) }}" x-data="{busy:false}" @submit="busy=true">@csrf<button class="btn small" :disabled="busy"><i data-lucide="refresh-cw" size="14" :class="busy&&'spin'"></i><span x-text="busy?'Se verifică…':'Verifică acum'">Verifică acum</span></button></form>@else<span class="muted">—</span>@endif</td>
</tr>
@endforeach
</tbody></table></div></section>
@if(session('verification_result')) @php($result=session('verification_result'))
<div class="verify-modal" x-data="{open:true}" x-show="open" x-cloak @keydown.escape.window="open=false" role="dialog" aria-modal="true" aria-labelledby="verify-title"><div class="verify-backdrop" @click="open=false"></div><section class="verify-dialog" x-show="open" x-transition><button class="verify-close" @click="open=false" aria-label="Închide"><i data-lucide="x" size="19"></i></button><div class="verify-heading"><span class="verify-icon {{ $result['status'] }}"><i data-lucide="{{ $result['status']==='healthy'?'circle-check-big':'triangle-alert' }}" size="25"></i></span><div><p class="eyebrow">Rezultatul verificării</p><h2 id="verify-title">{{ $result['name'] }}</h2><span class="source-status {{ $result['status'] }}"><span></span>{{ $result['status_label'] }}</span></div></div><div class="verify-meta"><span><i data-lucide="calendar-clock" size="13"></i>{{ $result['checked_at'] }}</span><span><i data-lucide="timer" size="13"></i>{{ number_format($result['duration']) }} ms</span></div><div class="verify-grid"><div><span>În baza de date</span><b>{{ number_format($result['database']) }}</b></div><div><span>Detectate la sursă</span><b>{{ number_format($result['detected']) }}</b></div><div class="metric-new"><span>Nou adăugate</span><b>+{{ number_format($result['new']) }}</b></div><div class="metric-updated"><span>Actualizate</span><b>{{ number_format($result['updated']) }}</b></div><div><span>Neschimbate</span><b>{{ number_format($result['unchanged']) }}</b></div><div class="metric-errors"><span>Erori</span><b>{{ number_format($result['errors']) }}</b></div></div><div class="verify-message"><i data-lucide="terminal" size="15"></i><span>{{ $result['message'] }}</span></div>@if($result['verification_only'])<div class="verify-info"><i data-lucide="info" size="16"></i><span>Aceasta a fost o verificare de disponibilitate. Nu s-a executat importul, de aceea valorile „nou adăugate” și „actualizate” sunt zero.</span></div>@endif<button class="btn" @click="open=false">Am înțeles</button></section></div>
@endif
@endsection
